client/networks/v1/networks/networks.go, gcore/network/v1/availablenetworks/requests.go
Support query params specified in API (https://apidocs.gcorelabs.com/cloud#operation/AvailableNetworkViewSet.get) in list-available networks.
=> support filter params in list available networks

Makefile
позволяет выполнить компиляцию под текущую архитектуру CPU
=> use local GOARCH. Apple M1 compatibility

gcore/baremetal/v1/bmcapacity/requests.go, gcore/baremetal/v1/bmcapacity/results.go, gcore/baremetal/v1/bmcapacity/testing/doc.go, gcore/baremetal/v1/bmcapacity/testing/fixtures.go, gcore/baremetal/v1/bmcapacity/testing/requests_test.go, gcore/baremetal/v1/bmcapacity/urls.go
* Add [check for available baremetal nodes](https://apidocs.gcorelabs.com/cloud#tag/instances/operation/BmCapacityHandler.get)
=> GCLOUD2-7583: Add check for available baremetal nodes

Makefile
* Now CLI always shows actual version of gcorelabscloud-go
=> Bug fix: show actual package version in CLI

auth_options.go, provider_client.go
This commit fixes:
1) Original error from token refresh request lost, so no errors related to token refresh returned.
2) Necessary field ("refresh"), containing refresh token missing, for some reason access token passed instead.
=> fix reauthenticate on token expiration

client/ais/v1/ais/ias.go, client/ais/v1/client/client.go, client/ais/v2/client/client.go, client/instances/v1/instances/instances.go, client/loadbalancers/v1/listeners/lsiteners.go, cmd/commands.go, gcore/ai/v1/aiflavors/requests.go, gcore/ai/v1/aiflavors/results.go, gcore/ai/v1/aiflavors/testing/docs.go, gcore/ai/v1/aiflavors/testing/fixtures.go, gcore/ai/v1/aiflavors/testing/requests_test.go, gcore/ai/v1/aiflavors/urls.go, gcore/ai/v1/aiimages/requests.go, gcore/ai/v1/aiimages/results.go, gcore/ai/v1/aiimages/testing/docs.go, gcore/ai/v1/aiimages/testing/fixtures.go, gcore/ai/v1/aiimages/testing/requests_test.go, gcore/ai/v1/aiimages/urls.go, gcore/ai/v1/ais/requests.go, gcore/ai/v1/ais/results.go, gcore/ai/v1/ais/testing/docs.go, gcore/ai/v1/ais/testing/fixtures.go, gcore/ai/v1/ais/testing/requests_test.go, gcore/ai/v1/ais/urls.go, gcore/flavor/v1/flavors/results.go, gcore/loadbalancer/v1/lbpools/testing/fixtures.go
Add support of AI cluster infrastructure
=> Gcloud2 11662 add ai support

gcore/ddos/v1/ddos/requests.go, gcore/ddos/v1/ddos/results.go, gcore/ddos/v1/ddos/testing/fixtures.go
GCLOUD2-9267 added and removed a few fields, but most importantly contained a backwards-incompatible change of `Profile.ProfileTemplate` from `int` to a nested object.
=> MKAAS-980 Update DDoS API to match changes from GCLOUD2-9267

gcore/baremetal/v1/bminstances/requests.go, gcore/ddos/v1/ddos/requests.go, gcore/ddos/v1/ddos/testing/fixtures.go, gcore/ddos/v1/ddos/testing/options_test.go, gcore/ddos/v1/ddos/testing/requests_test.go, gcore/instance/v1/instances/requests.go, gcore/instance/v1/instances/results.go, gcore/loadbalancer/v1/loadbalancers/requests.go, gcore/loadbalancer/v1/loadbalancers/results.go
Adds:
- `ResourceID` and `ResourceType` fields to `CreateProfileOpts` enabling DDoS profile support for load balancers and VM instances.
- `WithDdos` option to listing load balancers, instances and bminstances.
- Optional `DdosProfile` field to load balancers and instances.
=> MKAAS-981 Add support for DDoS profiles on load balancers

gcore/loadbalancer/v1/lbpools/requests.go
Patch load balancer pool now supports protocol change. 
New field has been added to lbpools.UpdateOpts to support this API change with gcorelabscloud-go client.
=> Add "Protocol" to lbpool update opts

gcore/volume/v1/volumes/types.go
The validation in custom VolumeType.Unmarshal prevents decoding empty / null values.
=> GCLOUD2-12829 Remove validation from VolumeType Unmarshal

gcore/loadbalancer/v1/loadbalancers/requests.go
**Changelog:**
- Add missing load balancer list opts.
We were missing `logging_enabled` and recently added `name` (filtering by name, quite useful). See [docs](https://api.gcore.com/docs/cloud#tag/Load-Balancers/operation/LoadBalancerViewSet.get) for the full list.
=> MKAAS-1129 Add missing load balancer list opts

gcore/loadbalancer/v1/loadbalancers/results.go, gcore/loadbalancer/v1/loadbalancers/testing/fixtures.go
**Changelog:**
- Add missing `additional_vips` field to load balancer struct.
The field was added to the API in GCLOUD2-12568, but it looks like we missed it in GCLOUD2-12605 PRs.
=> MKAAS-1129 Add missing additional_vips field in load balancers

client/k8s/v2/k8s/pools.go, gcore/k8s/v2/pools/requests.go, gcore/k8s/v2/pools/results.go, gcore/k8s/v2/pools/testing/fixtures.go, gcore/k8s/v2/pools/testing/requests_test.go
**Changelog:**
- Add labels/taints support to cluster pool APIs.
- Update uses ptrs to support clearing labels/taints with empty maps ([playground](https://go.dev/play/p/s1PMiyZUW7K)).
- Make `AutoHealingEnabled` a ptr to support sending `false` value.
=> MKAAS-1268 Add missing update pool opts

gcore/k8s/v2/pools/requests.go
Changelog:
- Added missing `omitempty` tag to `pools.CreateOpts.ServerGroupPolicy` field.
=> GCLOUD2-14457 Fix sending empty servergroup_policy value

gcore/k8s/v2/clusters/requests.go, gcore/k8s/v2/clusters/results.go, gcore/k8s/v2/clusters/urls.go, gcore/k8s/v2/pools/requests.go, gcore/k8s/v2/pools/results.go
**Changelog:**
- Add `Authentication.OIDC` settings to k8s clusters.
- Add `AutoscalerConfig` settings to k8s clusters.
- Add Hubble Relay / Hubble UI switches for k8s clusters using Cilium CNI.
- Add `CrioConfig` and `KubeletConfig` settings to k8s cluster pools.
- Add support for k8s `clusters.Update` request (authentication and autoscaler configuration).
- Fix typo in `Cilium.LoadBalancerMode` tag (`omitemtpy` => `omitempty`).
=> MKAAS-1283 Add support for advanced k8s settings

gcore/loadbalancer/v1/loadbalancers/requests.go, gcore/region/v1/regions/testing/fixtures.go
**Changelog**
- Added missing pool timeouts and health monitor expected codes to batch load balancer create request. We already had them for pool create but not batch lb create.
- Fixed build.
=> GCLOUD2-14662 Add missing timeouts to create pool opts

gcore/file_share/v1/file_shares/results.go
**Changelog**
- Add `subnet_id` to sfs file share responses.
=> MKAAS-1327 Add subnet id to file shares

client/flags/flags.go, client/k8s/v2/client/client.go, client/k8s/v2/k8s/clusters.go, client/k8s/v2/k8s/pools.go, gcore/k8s/v2/clusters/requests.go, gcore/k8s/v2/clusters/testing/requests_test.go, gcore/k8s/v2/clusters/urls.go
**Changelog**
- Add support for k8s cluster create_versions and upgrade_versions APIs.
- Add `create-versions` and `upgrade-versions` subcommands to `./gcoreclient cluster` cmd.
- Fix `ERRO[0000] Cannot initialize application: allowed values are token, platform` error when trying to use API Token with gcoreclient CLI.
=> MKAAS-1438 Add k8s create/upgrade versions APIs

gcore/file_share/v1/file_shares/results.go
**Changelog**
- Added `network_id` to `file_shares` responses.
=> MKAAS-1327 Add network id to file shares

gcore/file_share/v1/file_shares/requests.go, gcore/file_share/v1/file_shares/testing/fixtures.go, gcore/file_share/v1/file_shares/testing/network_test.go
Now we can omit subnet id when creating a file share
=> GCLOUD2-16691 Subnet is optional when creating a sfs

.goreleaser.yml, Makefile, provider_client.go
The default UserAgent was being set with an incorrect default value, this MR sets the default with the value coming from the release version.
=> GCLOUD2-14671 Set correct AppVersion in request's User-Agent header and cmd version

.github/workflows/release.yml
Currently, developers manage the `AppVersion` manually, and before each new release, it needs to be updated. This PR adds a step to the **release** workflow that compares the git tag version, associated with this new release, with the `AppVersion` specified in the code. If the versions don't match, the pipeline fails, and the release doesn't succeed.
The goal is to make sure the versions match and to force the developer making a release to bump the `AppVersion` before making the release.
The `AppVersion` is located in [provider_client.go#L23](https://github.com/G-Core/gcorelabscloud-go/blob/2dfeed362704125ad8392d69f1f880cee4e9000e/provider_client.go#L23).
=> Add step to release pipeline to check that tag version matches AppVersion

.github/workflows/build.yml
Appending the commit ID to the name of the binary allows the distinction between builds.
=> Append the commit id to the build upload artifact

client/ais/v1/ais/ias.go, gcore/ai/v1/ais/requests.go
This PR adds the ability to create GPU clusters with more than one instance, which is the default. The following changes were made:
- new CLI option `instances-count` for specifying the desired number of instances, if not provided the default value of 1 will be used.
- new `InstancesCount` field in the `CreateOpts` struct of the SDK for allowing one to create a cluster with more than one instance using the SDK.
Why this change is needed?
1. Provide users with the ability to create a cluster with multiple instances.
2. Allow the cluster resize operation in the [terraform-provider-gcore](https://github.com/G-Core/terraform-provider-gcorel).
The API endpoint for this operation can be found [here](https://api.gcore.com/docs/cloud#tag/GPU-Cloud/operation/AIClustersGPUHandler.post). The API …
=> Add instances count argument to GPU cluster creation

client/ais/v1/ais/ias.go, client/flags/flags.go, gcore/ai/v1/ais/requests.go, gcore/ai/v1/ais/urls.go
This PR allows deleting a node from an existing GPU cluster. The following changes were made:
- new SDK function `DeleteNodeFromGPUCluster` for deleting a node from a GPU cluster
- new CLI subcommand `delete-node` that performs the same operation.
Example command:
```bash
gcoreclient ai delete-node <cluster_id> <instance_id>
``` 
Sample output:
```
{
"tasks": [
"542888dc-04ed-4a0b-bd90-66944ecbfad7"
]
}
```
The respective API endpoint can be found [here](https://api.gcore.com/docs/cloud#tag/GPU-Cloud/operation/AIClustersNodeDelete.delete).
=> GCLOUD2-17736 Add support for deleting a node from a GPU cluster

client/ais/v1/ais/ias.go, gcore/ai/v1/ais/requests.go, gcore/ai/v1/ais/testing/fixtures.go, gcore/ai/v1/ais/testing/requests_test.go
Refactor the `resize` command to send requests to the [AIClustersGPUResize](https://api.gcore.com/docs/cloud#tag/GPU-Cloud/operation/AIClustersGPUResizeHandler.post) endpoint, instead of the legacy AIClustersResize endpoint.
New usage of the command:
```bash
gcoreclient ai resize --instances-count 2 "<CLUSTER_ID"
```
=> GCLOUD2-17734 Refactor resize cmd to target AI GPU endpoint

client/tasks/v1/tasks/tasks.go, gcore/task/v1/tasks/requests.go, gcore/task/v1/tasks/results.go, gcore/task/v1/tasks/testing/requests_test.go, gcore/task/v1/tasks/urls.go
This PR builds on top of #166 and makes the necessary changes such that the SDK maintains backward compatibility, namely the following changes are made:
- `tasks.List()` maintains the same interface as before so that there are no breaking changes, and is marked as `Deprecated` guiding SDK users that they should use either `tasks.ListActive()` or `tasks.ListWithOpts()`, see more details below.
- new `tasks.ListActive()` function that returns the *active* tasks and targets the [List active tasks](https://api.gcore.com/docs/cloud#tag/Tasks/operation/TasksActiveInProjectViewSet.get) API endpoint.
- new `tasks.ListWithOpts()` function that accepts the additional parameter `opts ListOptsBuilder`, which allows tasks to be filtered by a predefined set of filters (projectID, state, taskType, ...). …
=> GCLOUD2-17888 Add ability to List tasks with filter options

errors.go, results.go
This PR adds the `request_id` to the error message of requests made to the Cloud API.
The following example shows how the error message looks like when using the SDK, for querying a Task with a non-existing id (`"f19f3966-07fb-432d-8a5d-dfd2d3f771a8"`):
```go
import (
....
"github.com/G-Core/gcorelabscloud-go/gcore/task/v1/tasks"
"log"
)
... 
r := tasks.Get(client, "f19f3966-07fb-432d-8a5d-dfd2d3f771a8")
if r.Err != nil {
log.Fatalf("Failed to get task: %v", r.Err)
}
```
the output will be:
```
2025/02/21 15:09:12 Failed to get task: The task(f19f3966-07fb-432d-8a5d-dfd2d3f771a8) not found. RequestID: ca8ff73e0cf17866b8dfc267052710fc
```
Similarly, when using the `gcoreclient` CLI:
```bash
> gcoreclient task show f19f3966-07fb-432d-8a5d-dfd2d3f771a8
The …
```
=> GCLOUD2-17779 Add request_id to error message

provider_client.go
This PR allows one to enable retries for GET requests on 5XX failures. This feature is enabled in the provider client, given that most SDK methods do not provide a `RequestOpts` parameter, which would allow configuring a retry policy on a more granular level.
How to enable retries? (by default they are disabled)
```go
...
provider, err := gcore.AuthenticatedClient(gcorecloud.AuthOptions{
APIURL:      os.Getenv("GCLOUD_API_URL"),
....
})
// enable retries with a maximum of 3 attempts and a base interval of 2 seconds
// example of retry intervals with this configuration: 1s, 3s and 7s.
provider.EnableGetRetriesOn5XX(3, 2)
```
Which operations are retried when this feature is enabled?
- `GET` requests
- `5xx` errors
=> GCLOUD2-18186 Add ability to config Get Retries for 5XX errors in the provider client

gcore/gpu/v3/clusters/requests.go
Add the ability to rename a GPU cluster using the SDK.
How to test:
- First, create a GPU cluster, and then use the following snippet and fill in the `cluster_id` of the created cluster.
```go
import (
...
"github.com/G-Core/gcorelabscloud-go/gcore/gpu/v3/clusters"
...
)
func main() {
client, err := gcore.ClientServiceFromProvider(provider, gcorecloud.EndpointOpts{
Name:    "gpu/virtual",
Region:  <region_id>,
Project: <project_id>,
Version: "v3",
})
if err != nil {
log.Fatalf("Failed to create client: %v", err)
}
clusterID := "<cluster_id>"
result := clusters.Get(client, clusterID)
if result.Err != nil {...}
cluster, err := result.Extract()
if err != nil {...}
fmt.Printf("Cluster name: %s\n", cluster.Name)
opts := clusters.RenameClusterOpts{
Name: "new-cluster-name",
}
result = …
```
=> GCLOUD2-18370 Add GPU Cluster Rename

.goreleaser.yml
Renames the binary in the release archives to `gcoreclient`as requested in https://github.com/G-Core/gcorelabscloud-go/issues/21.
=> Rename release binary to gcoreclient

client/regionsaccess/v1/regionsaccess/regionsaccess.go
Fix the duplication issue in the `gcoreclient` where there were two entries for a `region` command:
- `gcoreclient region` GCloud regions API
- `gcoreclient regionaccess` GCloud regions access API (fixed)
This issue prevented access to the regions access API using the `gcoreclient`.
=> Rename regionaccess command 

client/gpu/v3/clusters/clusters.go, gcore/gpu/v3/clusters/requests.go
Add the ability to Delete a GPU cluster using the SDK and the CLI.
How to test using the CLI:
```bash
gcoreclient gpu virtual clusters delete <cluster_id>
```
=> GCLOUD2-18413 Add GPU Delete cluster

client/gpu/v3/clusters/clusters.go, client/utils/utils.go, gcore/gpu/v3/clusters/requests.go, gcore/gpu/v3/clusters/types.go, gcore/gpu/v3/clusters/urls.go
Add the ability to Create a GPU cluster using the SDK and the CLI.
Using the CLI only it's possible to attach one volume and interface. Furthermore, the volume needs to be of source `image`.
How to test using the CLI:
```bash
./gcoreclient gpu virtual clusters create \
--name "MyTestCluster" \
--flavor "<flavor_id>" \
--tags "source=cli" \
--servers-count 1 \
--interface-type "external" \
--interface-name "MyTestCluster" \
--volume-name "MyImageTestVolume" \
--volume-size 50 \
--volume-type "standard" \
--volume-tags "creator=po" \
--volume-image-id "<image_id>" \
--server-username "admin" \
--server-password "pwd"
```
=> GCLOUD2-18478 Add GPU Create cluster

gcore/instance/v1/instances/requests.go
Adding missing `include_ai` query param to listing instances API ([docs](https://api.preprod.world/docs/cloud#tag/Instances/operation/InstanceViewSetV1.get)). While marked as deprecated, we need it to allow GCCM to see GPU nodes in MKaaS and there's currently no good alternative.
Required to fix GCLOUD2-18543.
=> GCLOUD2-18655 Add support for listing GPU instances

client/gpu/v3/clusters/clusters.go, gcore/gpu/v3/clusters/requests.go, gcore/gpu/v3/clusters/results.go
Add an ability to list GPU clusters via SDK and CLI.
To test:
```go
import (
"fmt"
gcorecloud "github.com/G-Core/gcorelabscloud-go"
"github.com/G-Core/gcorelabscloud-go/gcore"
"github.com/G-Core/gcorelabscloud-go/gcore/gpu/v3/clusters"
"log"
)
func main() {
client, err := gcore.ClientServiceFromProvider(provider, gcorecloud.EndpointOpts{
Name:    "gpu/virtual",
Region:  <region_id>,
Project: <project_id>,
Version: "v3",
})
if err != nil {
log.Fatalf("Failed to create client: %v", err)
}
opts := clusters.ListOpts{}
result := clusters.List(client, opts)
if result.Err != nil {
fmt.Printf("Failed to list clusters: %v", result.Err)
}
cluster_list, err := result.AllPages()
if err != nil {
fmt.Printf("Failed to get all pages: %v", err)
}
fmt.Printf("Clusters: %+v", cluster_list)
}
```
=> GCLOUD2-17858 Add list GPU clusters

gcore/ai/v1/ais/requests.go, gcore/ai/v1/ais/testing/fixtures.go, gcore/ai/v1/ais/testing/requests_test.go
1. Fixed an issue with passing metadata to v1 create ai cluster request. The `dive` validator without anything following it caused `panic: runtime error: invalid memory address or nil pointer dereference`.
2. `DeleteNodeFromGPUCluster` now accepts `DeleteNodeOptsBuilder` instead of `DeleteNodeOpts` as it should from the beginning.
Both changes are entirely backwards compatible, requiring no changes in existing code.
None
=> MKAAS-1518 Fix AI metadata and delete node opts

gcore/gpu/v3/clusters/results.go
This PR performs the following changes:
- Add `ExtractGPUClusterIDFromTask` utility function that allows the extraction of the `cluster_id` from a Task.
- Make `UserData` a pointer (so it can be nil) in the Virtual GPU get/list cluster responses.
=> GCLOUD2-18391 Add extract from task

gcore/gpu/v3/clusters/types.go
This PR fixes the following error:
```
$ gcoreclient api-token gpu baremetal clusters list
invalid ClusterStatusType type: resizing
exit status 1
```
I added missing bare metal GPU cluster statuses (`resizing` and `deleting`).
I also removed validation from unmarshaling all GPU cluster related enums, because the root cause is having response validation.
IMHO we should validate requests, but never responses. That's because response validation on the SDK side turns any additive change on the backend (e.g. adding a new enum field) into a breaking change for existing code running older versions of the SDK.
=> MKAAS-1568 Fix listing gpu clusters in resizing state

client/gpu/v3/clusters/clusters.go, client/utils/utils.go, gcore/gpu/v3/clusters/requests.go
This PR improves how users can manage tags for virtual GPU clusters. Now, users are able to delete specific tags or even to remove all tags at once. The following methods have been added to the `clusters` package:
- `RemoveTags` remove a list of tags
- `RemoveAllTags` remove all tags 
- `UpdateAndRemoveTags` add, replace and delete a set of tags (provide `nil` values for tag keys to delete). 
The `gcoreclient` CLI has also been update with a new `--remove-tags` command that allows users to remove multiple tags from a gpu cluster:
```bash
gcoreclient gpu virtual clusters updatetags --tags env=dev --remove-tags owner --remove-tags region <cluster_id>
```
Fixes # (issue)
=> GCLOUD2-19947 Improve management of virtual gpu cluster tags

client/file_shares/v1/file_shares/file_shares.go, gcore/file_share/v1/file_shares/requests.go, gcore/file_share/v1/file_shares/testing/requests_test.go
This PR enables users to manage tags in file shares; before, users could only create a file share with tags, but these couldn't be changed. The changes introduced allow adding, replacing, or removing tags using the SDK methods or the CLI.
The previous struct `UpdateOpts` and `Update` method have been deprecated, and users should use the following new methods:
- `UpdateWithTags` allows updating all fields (which are available for updating) in a single request, including `tags`
- `Rename` for only updating the name of a file share
- `UpdateTags` for adding or replacing tags
- `RemoveTags` for removing a list of tags
- `RemoveAllTags` for removing all tags
- `UpdateAndRemoveTags` for adding, replacing, and removing tags in a single request.
=> GCLOUD2-19495 Add support for tags in file shares

client/gpu/v3/clusters/clusters.go, gcore/gpu/v3/clusters/requests.go, gcore/gpu/v3/clusters/results.go, gcore/gpu/v3/servers/types.go, provider_client.go
Added support for recently introduced security groups in bare metal GPU clusters.
The v3 APIs changed from accepting and returning `[]string` to objects with `id` and `name` fields respectively.
None
=> GCLOUD2-20199 Support sec groups for bare metal gpu clusters

gcore/inference/v3/credentials/results.go, gcore/inference/v3/credentials/testing/fixtures.go, gcore/inference/v3/credentials/testing/requests_test.go, provider_client.go
We removed `password` field from responses for all inference registry credentials handlers. This PR also revomes it from SDK structures.
Fixes # (issue)
=> Remove password field from registry credential results

gcore/ai/v1/ais/results.go, gcore/ai/v1/ais/testing/fixtures.go
Fix security group structure for AI clusters - change from string array to structured format
This PR fixes the security group structure inconsistency in AI clusters. Previously, security groups were returned as a list of strings, but they should be returned as structured objects to match the expected API format and maintain consistency with other cluster types.
**Changes made:**
- Updated `PoplarInterfaceSecGrop.SecurityGroups` from `[]string` to `[]gcorecloud.ItemName` in AI cluster results
- Modified test fixtures to use the new object structure format
- Ensured consistency between request format (`[{"id": "uuid"}]`) and response format (`[{"name": "name"}]`)
**Before:**
```json
"security_groups": ["uuid-string-1", "uuid-string-2"]
```
**After:**
```json
"security_groups": [{"name": …
```
=> Update security group representation in results

client/gpu/v3/flavors/commands.go, gcore/gpu/v3/flavors/results.go
This PR adds support for the `supported_features` field in GPU flavors API responses, addressing the missing functionality in the SDK where GPU flavors did not include the `supported_features` field as documented in the API specification.
**Changes made:**
- Added `SupportedFeatures` struct with `SecurityGroups bool` field
- Updated `BMFlavor` and `VMFlavor` structs to include `SupportedFeatures *SupportedFeatures` field
- Updated CLI output structures (`BMFlavorOutput` and `VMFlavorOutput`) to display supported features
- Updated conversion logic in CLI commands to properly handle the new field
**API Documentation Reference:**
https://gcore.com/docs/api-reference/cloud/gpu-cloud/list-bare-metal-gpu-flavors#response-results-supported-features
The `supported_features` object contains a set …
=> GCLOUD2-20322 Add SupportedFeatures to flavor output structures

client/file_shares/v1/file_shares/file_shares.go, gcore/file_share/v1/file_shares/requests.go, gcore/file_share/v1/file_shares/results.go
⚠️ This is a breaking change - Any existing code that was using the VolumeType field will need to be updated to use TypeName instead.
This PR removes the `volume_type` field from File Shares and consolidates functionality to use only `type_name`. This change eliminates redundancy where both `volume_type` and `type_name` were representing the same information.
**Changes made:**
- Removed `VolumeType` field from `CreateOpts` struct
- Removed `VolumeType` field from `FileShare` struct  
- Simplified validation logic to use only `TypeName`
- Updated validation to use correct API values: `standard` and `vast`
- Updated CLI to use `--type-name` flag directly with API values
- Removed all backward compatibility/mapping logic
- Updated all business logic to use `type_name` exclusively
**Files …
=> GCLOUD2-20153  Refactor file share creation options to use TypeName instead of VolumeType and update related validation logic

client/gpu/v3/clusters/clusters.go, gcore/gpu/v3/clusters/requests.go, gcore/gpu/v3/clusters/types.go, pagination/pager.go
Added `managed_by` query param to GPU clusters list opts. Optional. Default behavior unchanged.
Examples:
```sh
gcoreclient api-token gpu baremetal clusters list
gcoreclient api-token gpu baremetal clusters list --managed-by=user
gcoreclient api-token gpu baremetal clusters list --managed-by=k8s
```
None
=> MKAAS-1623 Add managed_by opt to list gpu clusters

client/gpu/v3/clusters/clusters.go, client/gpu/v3/servers/servers.go, gcore/gpu/v3/clusters/requests.go
This PR performs the following changes:
- decouples Baremetal and Virtual GPU cluster creation in the SDK, by creating new Opts types for Baremetal GPU clusters (require an `image_id`as input and don't expect to receive `volumes` inside `server_settings`).
- adds a command for creating Baremetal GPU clusters: `gcoreclient gpu baremetal cluster create`
- removes the flag `delete-all-volumes` from the `delete` command for Baremetal GPU clusters
- adds a command for updating tags of Baremetal GPU clusters: `gcoreclient gpu baremetal cluster updatetags`
Fixes # (issue)
=> GCLOUD2-20099 Add Baremetal GPU cluster creation
