G-Core/gcorelabscloud-go

client/ports/v1/client/client.go
client/ports/v1/ports/ports.go
cmd/gcoreclient/main.go
gcore/instance/v1/instances/results.go
gcore/instance/v1/instances/testing/fixtures.go
gcore/port/v1/ports/requests.go
gcore/port/v1/ports/results.go
gcore/port/v1/ports/testing/fixtures.go
gcore/port/v1/ports/testing/requests_test.go
gcore/port/v1/ports/urls.go

support /v1/ports for enabling\disabling port security

support ports v1 api

---

Makefile
README.md
client/instances/v1/client/client.go
client/instances/v1/instances/instances.go
client/l7policies/v1/client/client.go
client/l7policies/v1/l7policies/l7policies.go
client/l7policies/v1/l7rules/l7rules.go
client/reservedfixedips/v1/client/client.go
client/reservedfixedips/v1/reservedfixedips/reservedfixedips.go
client/routers/v1/client/client.go
client/routers/v1/routers/routers.go
client/subnets/v1/subnets/subnets.go
cmd/gcoreclient/main.go
gcore/instance/v1/instances/requests.go
gcore/instance/v1/instances/testing/requests_test.go
gcore/loadbalancer/v1/l7policies/requests.go
gcore/loadbalancer/v1/l7policies/testing/requests_test.go
gcore/router/v1/routers/requests.go

README.md updated
instances attach/detach interface and test fixed
makefile fixed
reservedfixedip cmd added
routers added cmd added
l7policy and l7rule cli added

added new cli command

---

client/loadbalancers/v1/lbpools/lbpools.go
client/loadbalancers/v1/listeners/lsiteners.go
gcore/loadbalancer/v1/lbpools/requests.go
gcore/loadbalancer/v1/lbpools/results.go

Support for expected_codes field of healthmonitor

GCLOUD2-3228

---

client/secrets/v1/client/client.go
client/secrets/v1/secrets/secrets.go
cmd/gcoreclient/main.go
gcore/loadbalancer/v1/listeners/requests.go
gcore/loadbalancer/v1/listeners/results.go
gcore/loadbalancer/v1/loadbalancers/requests.go
gcore/secret/v1/secrets/requests.go
gcore/secret/v1/secrets/results.go
gcore/secret/v1/secrets/testing/fixtures.go
gcore/secret/v1/secrets/testing/requests_test.go
gcore/secret/v1/secrets/types.go
gcore/secret/v1/secrets/urls.go
gcore/servergroup/v1/servergroups/requests.go
gcore/servergroup/v1/servergroups/types.go
results.go

added secret_id to lb listener

secrets added

---

client/loadbalancers/v1/lbpools/lbpools.go
client/loadbalancers/v1/loadbalancers/loadbalancers.go
client/networks/v1/networks/networks.go
client/ports/v1/ports/ports.go
client/securitygroups/v1/securitygroups/securitygroups.go
gcore/loadbalancer/v1/lbpools/requests.go
gcore/loadbalancer/v1/lbpools/results.go
gcore/loadbalancer/v1/lbpools/testing/fixtures.go
gcore/loadbalancer/v1/lbpools/testing/requests_test.go
gcore/loadbalancer/v1/lbpools/urls.go
gcore/loadbalancer/v1/loadbalancers/requests.go
gcore/loadbalancer/v1/loadbalancers/results.go
gcore/loadbalancer/v1/loadbalancers/testing/fixtures.go
gcore/loadbalancer/v1/loadbalancers/testing/requests_test.go
gcore/loadbalancer/v1/loadbalancers/urls.go
gcore/network/v1/networks/requests.go
gcore/network/v1/networks/results.go
gcore/network/v1/networks/testing/fixtures.go
gcore/network/v1/networks/testing/requests_test.go
gcore/network/v1/networks/urls.go
gcore/port/v1/ports/requests.go
gcore/port/v1/ports/results.go
gcore/port/v1/ports/testing/fixtures.go
gcore/port/v1/ports/testing/requests_test.go
gcore/port/v1/ports/urls.go
gcore/securitygroup/v1/securitygrouprules/requests.go
gcore/securitygroup/v1/securitygroups/requests.go
gcore/securitygroup/v1/securitygroups/results.go
gcore/securitygroup/v1/securitygroups/testing/requests_test.go
gcore/securitygroup/v1/securitygroups/urls.go

assign allowed address pairs method added
list of instance ports method added
lb pool healthmonitor create/delete added
methods for lb custom security group added
securitygroups.DeepCopy added

lb and sg methods updated

---

client/apptemplates/v1/apptemplates/apptemplates.go
client/apptemplates/v1/client/client.go
client/regionsaccess/v1/client/client.go
client/regionsaccess/v1/regionsaccess/regionsaccess.go
client/schedules/v1/client/client.go
client/schedules/v1/schedules/schedules.go
cmd/gcoreclient/main.go
gcore/apptemplate/v1/apptemplates/requests.go
gcore/apptemplate/v1/apptemplates/results.go
gcore/apptemplate/v1/apptemplates/testing/fixtures.go
gcore/apptemplate/v1/apptemplates/testing/requests_test.go
gcore/apptemplate/v1/apptemplates/urls.go
gcore/floatingip/v1/floatingips/results.go
gcore/lifecyclepolicy/v1/lifecyclepolicy/types.go
gcore/regionaccess/v1/regionsaccess/requests.go
gcore/regionaccess/v1/regionsaccess/results.go
gcore/regionaccess/v1/regionsaccess/testing/fixtures.go
gcore/regionaccess/v1/regionsaccess/testing/requests_test.go
gcore/regionaccess/v1/regionsaccess/urls.go
gcore/schedule/v1/schedules/requests.go
gcore/schedule/v1/schedules/results.go
gcore/schedule/v1/schedules/testing/fixtures.go
gcore/schedule/v1/schedules/testing/requests_test.go
gcore/schedule/v1/schedules/urls.go

apptemplates added
schedule added
region_access added

api updated

---

gcore/ddos/v1/ddos/requests.go
gcore/ddos/v1/ddos/results.go
gcore/ddos/v1/ddos/testing/doc.go
gcore/ddos/v1/ddos/testing/fixtures.go
gcore/ddos/v1/ddos/testing/options_test.go
gcore/ddos/v1/ddos/testing/requests_test.go
gcore/ddos/v1/ddos/urls.go
go.mod
go.sum

Added DDoS protection endpoints support

GCLOUD2-6854: DDoS endpoints support

---

client/networks/v1/networks/networks.go
gcore/floatingip/v1/availablefloatingips/testing/fixtures.go
gcore/network/v1/networks/requests.go
gcore/network/v1/networks/results.go
gcore/network/v1/networks/testing/fixtures.go
gcore/network/v1/networks/testing/requests_test.go
gcore/network/v1/networks/urls.go
gcore/securitygroup/v1/securitygroups/testing/fixtures.go
gcore/securitygroup/v1/securitygroups/testing/requests_test.go
gcore/subnet/v1/subnets/requests.go
gcore/subnet/v1/subnets/results.go
gcore/subnet/v1/subnets/testing/fixtures.go
gcore/subnet/v1/subnets/testing/requests_test.go
gcore/subnet/v1/subnets/urls.go
gcore/utils/common.go
gcore/utils/metadata/requests.go
gcore/utils/metadata/results.go
gcore/utils/metadata/urls.go

Added metadata support for nets and subnets

net_subnet_metadata support

---

gcore/loadbalancer/v1/loadbalancers/requests.go
gcore/servergroup/v1/servergroups/requests.go
gcore/servergroup/v1/servergroups/testing/fixtures.go
gcore/servergroup/v1/servergroups/testing/requests_test.go

Loadbalancer CreateOpts updated

GCLOUD2-8354 servergroup delete response updated

---

gcore/ddos/v1/ddos/requests.go
gcore/ddos/v1/ddos/results.go
gcore/ddos/v1/ddos/testing/fixtures.go
gcore/ddos/v1/ddos/testing/requests_test.go

* fixed a few minor bugs
* added new fields from the [API](https://apidocs.gcore.com/cloud#tag/ddos/operation/ProfilesHandler.get)

GCLOUD2-6855: DDoS protection fixes and update to the latest API

---

gcore/loadbalancer/v1/types/types.go

Add prometheus protocol type for LB listener.

Add prometheus protocol type for LB listener

---

gcore/region/v1/regions/results.go

Add `zone` field to `Regions` API.

add zone field to regions

---

client/instances/v1/instances/instances.go

Fixed help and stdout output of command:
`gcoreclient instance create`

Fix "instance create" output

---

gcore/instance/v1/instances/requests.go
gcore/instance/v1/instances/testing/fixtures.go
gcore/instance/v1/instances/testing/options_test.go
gcore/instance/v1/instances/testing/requests_test.go

Add volume metadata for creating instance

MKAAS-676 Add volume metadata for instance creation

---

gcore/instance/v1/instances/requests.go

Support DeleteOnTermination for instance CreateVolumeOpts

add DeleteOnTermination field to instance CreateVolumeOpts

---

gcore/servergroup/v1/servergroups/types.go

add support for SoftAffinityPolicy for ServerGroup

add SoftAffinityPolicy for ServerGroup

---

errors.go
provider_client.go

Added 502 and 504 error codes. We need this to carefully handle network and internal errors

MKAAS-796 Added 502 and 504 status codes

---

client/file_shares/v1/client/client.go
client/file_shares/v1/file_shares/file_shares.go
cmd/commands.go
gcore/file_share/v1/file_shares/doc.go
gcore/file_share/v1/file_shares/requests.go
gcore/file_share/v1/file_shares/results.go
gcore/file_share/v1/file_shares/testing/doc.go
gcore/file_share/v1/file_shares/testing/fixtures.go
gcore/file_share/v1/file_shares/testing/requests_test.go
gcore/file_share/v1/file_shares/urls.go
results.go

MKAAS-839 Add file share operations

---

client/loadbalancers/v1/client/client.go
client/loadbalancers/v1/listeners/lsiteners.go
gcore/loadbalancer/v1/listeners/requests.go
gcore/loadbalancer/v1/listeners/results.go
gcore/loadbalancer/v1/listeners/testing/fixtures.go
gcore/loadbalancer/v1/listeners/testing/requests_test.go
gcore/loadbalancer/v1/loadbalancers/requests.go

Add source acl for loadbalancer listeners

Add allowed_cidrs for listener to restict access to services

---

client/ais/v1/ais/ias.go
client/ais/v1/client/client.go
gcore/ai/v1/aiimages/requests.go
gcore/ai/v1/aiimages/results.go
gcore/ai/v1/ais/requests.go
gcore/ai/v1/ais/results.go

Add fixes for ai cluster operations

Add fixes for ai client

---

gcore/flavor/v1/flavors/results.go

Add OsType and Architecture fields for Flavor requests

Add OsType and Architecture fields for Flavor

---

client/images/v1/images/images.go
gcore/image/v1/images/requests.go

This PR adds support for setting image metadata and architecture via CLI

support setting image metadata and architecture via CLI

---

gcore/loadbalancer/v1/loadbalancers/requests.go
gcore/loadbalancer/v1/loadbalancers/results.go

Added missing logging configuration to Load Balancer create / update requests and get responses.

MKAAS-1087 Add missing logging opts to loadbalancers

---

gcore/k8s/v2/clusters/requests.go
gcore/k8s/v2/clusters/results.go
gcore/k8s/v2/clusters/types.go

Changelog:
Added support for different CNI.
Cloud-api already supports CNI selection. I added this feature to our client.

MKAAS-1126 Added cilium support

---

gcore/k8s/v2/clusters/results.go

Changelog:
Added fields with cirds for ivp4 and ipv6

MKAAS-1162 Added pods and services cidrs

---

client/loadbalancers/v1/loadbalancers/loadbalancers.go
client/loadbalancers/v1/testing/loadbalancers_test.go
gcore/loadbalancer/v1/loadbalancers/requests.go
gcore/loadbalancer/v1/loadbalancers/testing/requests_test.go

**Changelog:**
- Added missing GetOpts for loadbalancers.Get method (`show_stats` and `with_ddos`).

MKAAS-1129 Add missing LB get opts

---

gcore/loadbalancer/v1/loadbalancers/results.go

**Changelog:**
- Added missing `floating_ips` field to load balancer response.

MKAAS-1129 Add missing floating_ips field to load balancer response

---

gcore/k8s/v2/clusters/requests.go
gcore/k8s/v2/clusters/types.go
gcore/port/v1/ports/requests.go

Added support of native routing

Mkaas 1373 native routing

---

gcore/instance/v2/instances/requests.go
gcore/instance/v2/instances/testing/doc.go
gcore/instance/v2/instances/testing/fixtures.go
gcore/instance/v2/instances/testing/metadata_test.go
gcore/instance/v2/instances/testing/requests_test.go
gcore/instance/v2/instances/urls.go

Added support for getting and deleting instance metadata via item (v2)

GCLOUD2-16682 Added metadata item support for instances

---

client/gpu/v3/clusters/clusters.go
client/gpu/v3/commands.go
gcore/gpu/v3/clusters/requests.go
gcore/gpu/v3/clusters/results.go
gcore/gpu/v3/clusters/types.go
gcore/gpu/v3/clusters/urls.go

Add the ability to Get GPU clusters using the SDK and the CLI.
How to test using the CLI:
```bash
gcoreclient gpu virtual clusters show <cluster_id>
```

GCLOUD2-17860 Add GPU Get cluster

---

client/gpu/v3/commands.go
client/gpu/v3/volumes/commands.go
gcore/gpu/v3/volumes/requests.go
gcore/gpu/v3/volumes/results.go
gcore/gpu/v3/volumes/urls.go

- Introduced new commands for listing virtual GPU cluster volumes.
- Added necessary request and result handling for volume operations.
- Updated CLI to include volume commands in the GPU management interface.

Add volume management commands for GPU clusters

---

client/gpu/v3/commands.go
client/gpu/v3/servers/servers.go
gcore/gpu/v3/servers/requests.go
gcore/gpu/v3/servers/results.go
gcore/gpu/v3/servers/types.go
gcore/gpu/v3/servers/urls.go

- Introduced commands for listing virtual GPU cluster servers.
- Added server-related types, request handling, and result extraction.
- Updated CLI to include server commands in the GPU management interface.

Add GPU server management commands and related functionality

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature-request.yml
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md

- Created CONTRIBUTING.md to outline the development process, code style, and testing requirements.
- Updated README.md to include a link to the new contributing guidelines.
- Added pull request and issue templates for bug reports and feature requests to streamline contributions.

GCLOUD2-18005 Add contributing guidelines and issue templates

---

provider_client.go

Bump `AppVersion` before releasing.

Bump version to 0.18.0

---

gcore/k8s/v2/clusters/requests.go
gcore/k8s/v2/clusters/results.go
gcore/k8s/v2/clusters/types.go

Add support for Advanced DDoS Protection in Managed K8s.

MKAAS-1519 Add support for ddos profile in k8s cluster

---

provider_client.go

Bump `AppVersion` before releasing.

Bump version to 0.19.0

---

gcore/k8s/v2/pools/requests.go
provider_client.go

GCLOUD2-19174 increased max_node_count

---

provider_client.go

Bump the `AppVersion` before releasing.

Bump the version to 0.20.0

---

provider_client.go

Bump the `AppVersion` before release.

Bump the version to 0.21.0
